# Generated by Django 5.2.8 on 2025-11-19 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0006_alter_cart_updated_at_alter_cartitem_qauntity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='qauntity',
            new_name='quantity',
        ),
    ]
